# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{musician_analytics}
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["David Balatero"]
  s.date = %q{2010-06-04}
  s.description = %q{I wrote this quick library for aggregating analytics for my band, Operation ID. I wanted to track Last.fm, Twitter, and Myspace interactions over time. You might want to do this too!}
  s.email = %q{dbalatero@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.markdown",
     "README.markdown.html"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.markdown",
     "Rakefile",
     "VERSION",
     "lib/musician_analytics.rb",
     "lib/musician_analytics/lastfm.rb",
     "lib/musician_analytics/myspace.rb",
     "lib/musician_analytics/twitter.rb",
     "musician_analytics.gemspec",
     "spec/musician_analytics/lastfm_spec.rb",
     "spec/musician_analytics/myspace_spec.rb",
     "spec/musician_analytics/twitter_spec.rb",
     "spec/spec.opts",
     "spec/spec_helper.rb"
  ]
  s.homepage = %q{http://github.com/dbalatero/musician_analytics}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{Provides tools for programmer/musicians to quickly collect stats about their band.}
  s.test_files = [
    "spec/musician_analytics/lastfm_spec.rb",
     "spec/musician_analytics/myspace_spec.rb",
     "spec/musician_analytics/twitter_spec.rb",
     "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rspec>, [">= 1.2.9"])
      s.add_runtime_dependency(%q<monster_mash>, [">= 0"])
      s.add_runtime_dependency(%q<json>, [">= 0"])
    else
      s.add_dependency(%q<rspec>, [">= 1.2.9"])
      s.add_dependency(%q<monster_mash>, [">= 0"])
      s.add_dependency(%q<json>, [">= 0"])
    end
  else
    s.add_dependency(%q<rspec>, [">= 1.2.9"])
    s.add_dependency(%q<monster_mash>, [">= 0"])
    s.add_dependency(%q<json>, [">= 0"])
  end
end

